language: swift

language: swift  #1
osx_image: xcode6.4 #2
xcode_project: MovingHelper.xcodeproj #3
xcode_scheme: MovingHelper #4
xcode_sdk: iphonesimulator8.4 #5

osx_image: xcode11.6
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=13.3 name='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 name='iPhone 8'

script:
  - set -o pipefail && xcodebuild -project SFBottomSheet.xcodeproj -scheme SFBottomSheet -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
